### ISSUE TITLE
[FEATURE REQUEST] Ignroe auto generated codes for `goast eval`

### ISSUE THREAD

**Issue by Attsun1031** [m-mizutani/goast#2]
## Overview
It would be nicer if we can ignore auto generated files for `eval` command.

For example, since [ent](https://entgo.io/) generates many files and overwrites each time it generates, it is hard to keep valid codes if generated files violate our goast policy.

## Description of the feature
Exclude auto generated files if flag given, such as `--ignore-auto-generated`.

Go has [a convention about "Auto generated files"](https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source), so we can ignore it by regular expression.

`gosec` does it [here](https://github.com/securego/gosec/blob/7dcb8c74367c9b30c706991eb30c48e405a4cd62/analyzer.go#L306).

**Comment by m-mizutani** [comment]
Thank you for your suggestion. It looks good for me and let me implement.

**Comment by m-mizutani** [comment]
@Attsun1031 The feature to ignore auto generated has been released in [v0.1.0](https://github.com/m-mizutani/goast/releases/tag/v0.1.0). Let me close the issue.
